"".Add STEXT size=149 args=0x78 locals=0x28
	0x0000 00000 (bigAdd.go:5)	TEXT	"".Add(SB), ABIInternal, $40-120
	0x0000 00000 (bigAdd.go:5)	MOVQ	(TLS), CX
	0x0009 00009 (bigAdd.go:5)	CMPQ	SP, 16(CX)
	0x000d 00013 (bigAdd.go:5)	JLS	139
	0x000f 00015 (bigAdd.go:5)	SUBQ	$40, SP
	0x0013 00019 (bigAdd.go:5)	MOVQ	BP, 32(SP)
	0x0018 00024 (bigAdd.go:5)	LEAQ	32(SP), BP
	0x001d 00029 (bigAdd.go:5)	FUNCDATA	$0, gclocals·be3db15b186e8e86a4535b29564ff526(SB)
	0x001d 00029 (bigAdd.go:5)	FUNCDATA	$1, gclocals·f6bd6b3389b872033d462029172c8612(SB)
	0x001d 00029 (bigAdd.go:5)	FUNCDATA	$3, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x001d 00029 (bigAdd.go:5)	FUNCDATA	$4, "".Add.stkobj(SB)
	0x001d 00029 (bigAdd.go:5)	PCDATA	$2, $0
	0x001d 00029 (bigAdd.go:5)	PCDATA	$0, $0
	0x001d 00029 (bigAdd.go:5)	MOVQ	$0, "".~r2+128(SP)
	0x0029 00041 (bigAdd.go:5)	XORPS	X0, X0
	0x002c 00044 (bigAdd.go:5)	MOVUPS	X0, "".~r2+136(SP)
	0x0034 00052 (bigAdd.go:5)	MOVUPS	X0, "".~r2+152(SP)
	0x003c 00060 (bigAdd.go:6)	PCDATA	$2, $1
	0x003c 00060 (bigAdd.go:6)	PCDATA	$0, $1
	0x003c 00060 (bigAdd.go:6)	LEAQ	"".x+48(SP), AX
	0x0041 00065 (bigAdd.go:6)	MOVQ	AX, (SP)
	0x0045 00069 (bigAdd.go:6)	PCDATA	$2, $0
	0x0045 00069 (bigAdd.go:6)	MOVQ	AX, 8(SP)
	0x004a 00074 (bigAdd.go:6)	PCDATA	$2, $1
	0x004a 00074 (bigAdd.go:6)	PCDATA	$0, $2
	0x004a 00074 (bigAdd.go:6)	LEAQ	"".y+88(SP), AX
	0x004f 00079 (bigAdd.go:6)	PCDATA	$2, $0
	0x004f 00079 (bigAdd.go:6)	MOVQ	AX, 16(SP)
	0x0054 00084 (bigAdd.go:6)	CALL	math/big.(*Float).Add(SB)
	0x0059 00089 (bigAdd.go:6)	PCDATA	$2, $1
	0x0059 00089 (bigAdd.go:6)	MOVQ	24(SP), AX
	0x005e 00094 (bigAdd.go:6)	PCDATA	$0, $3
	0x005e 00094 (bigAdd.go:6)	MOVQ	(AX), CX
	0x0061 00097 (bigAdd.go:6)	MOVQ	CX, "".~r2+128(SP)
	0x0069 00105 (bigAdd.go:6)	MOVUPS	8(AX), X0
	0x006d 00109 (bigAdd.go:6)	MOVUPS	X0, "".~r2+136(SP)
	0x0075 00117 (bigAdd.go:6)	PCDATA	$2, $0
	0x0075 00117 (bigAdd.go:6)	MOVUPS	24(AX), X0
	0x0079 00121 (bigAdd.go:6)	MOVUPS	X0, "".~r2+152(SP)
	0x0081 00129 (bigAdd.go:6)	MOVQ	32(SP), BP
	0x0086 00134 (bigAdd.go:6)	ADDQ	$40, SP
	0x008a 00138 (bigAdd.go:6)	RET
	0x008b 00139 (bigAdd.go:6)	NOP
	0x008b 00139 (bigAdd.go:5)	PCDATA	$0, $-1
	0x008b 00139 (bigAdd.go:5)	PCDATA	$2, $-1
	0x008b 00139 (bigAdd.go:5)	CALL	runtime.morestack_noctxt(SB)
	0x0090 00144 (bigAdd.go:5)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 7c 48  dH..%....H;a.v|H
	0x0010 83 ec 28 48 89 6c 24 20 48 8d 6c 24 20 48 c7 84  ..(H.l$ H.l$ H..
	0x0020 24 80 00 00 00 00 00 00 00 0f 57 c0 0f 11 84 24  $.........W....$
	0x0030 88 00 00 00 0f 11 84 24 98 00 00 00 48 8d 44 24  .......$....H.D$
	0x0040 30 48 89 04 24 48 89 44 24 08 48 8d 44 24 58 48  0H..$H.D$.H.D$XH
	0x0050 89 44 24 10 e8 00 00 00 00 48 8b 44 24 18 48 8b  .D$......H.D$.H.
	0x0060 08 48 89 8c 24 80 00 00 00 0f 10 40 08 0f 11 84  .H..$......@....
	0x0070 24 88 00 00 00 0f 10 40 18 0f 11 84 24 98 00 00  $......@....$...
	0x0080 00 48 8b 6c 24 20 48 83 c4 28 c3 e8 00 00 00 00  .H.l$ H..(......
	0x0090 e9 6b ff ff ff                                   .k...
	rel 5+4 t=16 TLS+0
	rel 85+4 t=8 math/big.(*Float).Add+0
	rel 140+4 t=8 runtime.morestack_noctxt+0
"".init STEXT size=92 args=0x0 locals=0x8
	0x0000 00000 (<autogenerated>:1)	TEXT	"".init(SB), ABIInternal, $8-0
	0x0000 00000 (<autogenerated>:1)	MOVQ	(TLS), CX
	0x0009 00009 (<autogenerated>:1)	CMPQ	SP, 16(CX)
	0x000d 00013 (<autogenerated>:1)	JLS	85
	0x000f 00015 (<autogenerated>:1)	SUBQ	$8, SP
	0x0013 00019 (<autogenerated>:1)	MOVQ	BP, (SP)
	0x0017 00023 (<autogenerated>:1)	LEAQ	(SP), BP
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	FUNCDATA	$3, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001b 00027 (<autogenerated>:1)	PCDATA	$2, $0
	0x001b 00027 (<autogenerated>:1)	PCDATA	$0, $0
	0x001b 00027 (<autogenerated>:1)	MOVBLZX	"".initdone·(SB), AX
	0x0022 00034 (<autogenerated>:1)	CMPB	AL, $1
	0x0025 00037 (<autogenerated>:1)	JLS	48
	0x0027 00039 (<autogenerated>:1)	PCDATA	$2, $-2
	0x0027 00039 (<autogenerated>:1)	PCDATA	$0, $-2
	0x0027 00039 (<autogenerated>:1)	MOVQ	(SP), BP
	0x002b 00043 (<autogenerated>:1)	ADDQ	$8, SP
	0x002f 00047 (<autogenerated>:1)	RET
	0x0030 00048 (<autogenerated>:1)	JNE	57
	0x0032 00050 (<autogenerated>:1)	PCDATA	$2, $0
	0x0032 00050 (<autogenerated>:1)	PCDATA	$0, $0
	0x0032 00050 (<autogenerated>:1)	CALL	runtime.throwinit(SB)
	0x0037 00055 (<autogenerated>:1)	UNDEF
	0x0039 00057 (<autogenerated>:1)	MOVB	$1, "".initdone·(SB)
	0x0040 00064 (<autogenerated>:1)	CALL	math/big.init(SB)
	0x0045 00069 (<autogenerated>:1)	MOVB	$2, "".initdone·(SB)
	0x004c 00076 (<autogenerated>:1)	MOVQ	(SP), BP
	0x0050 00080 (<autogenerated>:1)	ADDQ	$8, SP
	0x0054 00084 (<autogenerated>:1)	RET
	0x0055 00085 (<autogenerated>:1)	NOP
	0x0055 00085 (<autogenerated>:1)	PCDATA	$0, $-1
	0x0055 00085 (<autogenerated>:1)	PCDATA	$2, $-1
	0x0055 00085 (<autogenerated>:1)	CALL	runtime.morestack_noctxt(SB)
	0x005a 00090 (<autogenerated>:1)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 46 48  dH..%....H;a.vFH
	0x0010 83 ec 08 48 89 2c 24 48 8d 2c 24 0f b6 05 00 00  ...H.,$H.,$.....
	0x0020 00 00 80 f8 01 76 09 48 8b 2c 24 48 83 c4 08 c3  .....v.H.,$H....
	0x0030 75 07 e8 00 00 00 00 0f 0b c6 05 00 00 00 00 01  u...............
	0x0040 e8 00 00 00 00 c6 05 00 00 00 00 02 48 8b 2c 24  ............H.,$
	0x0050 48 83 c4 08 c3 e8 00 00 00 00 eb a4              H...........
	rel 5+4 t=16 TLS+0
	rel 30+4 t=15 "".initdone·+0
	rel 51+4 t=8 runtime.throwinit+0
	rel 59+4 t=15 "".initdone·+-1
	rel 65+4 t=8 math/big.init+0
	rel 71+4 t=15 "".initdone·+-1
	rel 86+4 t=8 runtime.morestack_noctxt+0
go.loc."".Add SDWARFLOC size=0
go.info."".Add SDWARFINFO size=67
	0x0000 03 22 22 2e 41 64 64 00 00 00 00 00 00 00 00 00  ."".Add.........
	0x0010 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01 0f  ................
	0x0020 78 00 00 05 00 00 00 00 01 9c 0f 79 00 00 05 00  x..........y....
	0x0030 00 00 00 02 91 28 0f 7e 72 32 00 01 05 00 00 00  .....(.~r2......
	0x0040 00 00 00                                         ...
	rel 8+8 t=1 "".Add+0
	rel 16+8 t=1 "".Add+149
	rel 26+4 t=29 gofile../home/joshcarp/Documents/decimal-slides/examples/bigAdd.go+0
	rel 36+4 t=28 go.info.math/big.Float+0
	rel 47+4 t=28 go.info.math/big.Float+0
	rel 61+4 t=28 go.info.math/big.Float+0
go.range."".Add SDWARFRANGE size=0
go.isstmt."".Add SDWARFMISC size=0
	0x0000 04 0f 04 0e 03 0c 01 13 02 05 01 13 02 05 01 32  ...............2
	0x0010 02 0a 00                                         ...
go.loc."".init SDWARFLOC size=0
go.info."".init SDWARFINFO size=33
	0x0000 03 22 22 2e 69 6e 69 74 00 00 00 00 00 00 00 00  ."".init........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 00                                               .
	rel 9+8 t=1 "".init+0
	rel 17+8 t=1 "".init+92
	rel 27+4 t=29 gofile..<autogenerated>+0
go.range."".init SDWARFRANGE size=0
go.isstmt."".init SDWARFMISC size=0
	0x0000 04 0f 04 0c 03 07 01 05 02 09 01 02 02 13 01 10  ................
	0x0010 02 07 00                                         ...
"".initdone· SNOPTRBSS size=1
go.itab.*strings.Reader,io.ByteScanner SRODATA dupok size=40
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 7d 18 28 41 00 00 00 00 00 00 00 00 00 00 00 00  }.(A............
	0x0020 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 type.io.ByteScanner+0
	rel 8+8 t=1 type.*strings.Reader+0
	rel 24+8 t=1 strings.(*Reader).ReadByte+0
	rel 32+8 t=1 strings.(*Reader).UnreadByte+0
go.itablink.*strings.Reader,io.ByteScanner SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*strings.Reader,io.ByteScanner+0
type..importpath.math/big. SRODATA dupok size=11
	0x0000 00 00 08 6d 61 74 68 2f 62 69 67                 ...math/big
gclocals·be3db15b186e8e86a4535b29564ff526 SRODATA dupok size=16
	0x0000 04 00 00 00 0c 00 00 00 42 00 40 00 00 00 00 08  ........B.@.....
gclocals·f6bd6b3389b872033d462029172c8612 SRODATA dupok size=8
	0x0000 04 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
"".Add.stkobj SRODATA dupok size=40
	0x0000 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 28 00 00 00 00 00 00 00  ........(.......
	0x0020 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.math/big.Float+0
	rel 32+8 t=1 type.math/big.Float+0
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
